---
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - 80:80

    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jenkins
volumes:
  jenkins:
  nginx:

networks:
  jenkins:
